
ALTER TABLE public.leads
  ALTER COLUMN marca_modelo DROP NOT NULL,
  ALTER COLUMN preco_max DROP NOT NULL,
  ALTER COLUMN ano_min DROP NOT NULL,
  ALTER COLUMN tipo_carro DROP NOT NULL,
  ALTER COLUMN combustivel DROP NOT NULL,
  ALTER COLUMN caixa DROP NOT NULL,
  ALTER COLUMN urgencia DROP NOT NULL;

ALTER TABLE public.leads
  ADD COLUMN IF NOT EXISTS tipo_compra TEXT,
  ADD COLUMN IF NOT EXISTS forma_pagamento TEXT,
  ADD COLUMN IF NOT EXISTS tem_carro_especifico BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS ano_max INTEGER,
  ADD COLUMN IF NOT EXISTS km_max INTEGER,
  ADD COLUMN IF NOT EXISTS versao TEXT,
  ADD COLUMN IF NOT EXISTS cor TEXT,
  ADD COLUMN IF NOT EXISTS extras TEXT,
  ADD COLUMN IF NOT EXISTS marcas_preferidas TEXT,
  ADD COLUMN IF NOT EXISTS observacoes TEXT,
  ADD COLUMN IF NOT EXISTS retoma_marca TEXT,
  ADD COLUMN IF NOT EXISTS retoma_modelo TEXT,
  ADD COLUMN IF NOT EXISTS retoma_ano INTEGER,
  ADD COLUMN IF NOT EXISTS retoma_km INTEGER,
  ADD COLUMN IF NOT EXISTS retoma_estado TEXT,
  ADD COLUMN IF NOT EXISTS retoma_observacoes TEXT;
